modLoader="javafml"
loaderVersion="[4,)"
license = "MIT License"

[[mods]]
modId="weather_totems"
version="1.21.1-0.0"

displayName="Weather Totems"

logoFile = "logo.png"

authors = "Mattéo"

credits = "Silver Chariot (for the idea)"
description= '''
Add 3 totems to the game which change the weather
It's my very first public mod btw
'''

[[dependencies.weather_totems]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.weather_totems]]
    modId="minecraft"
    mandatory=true
    versionRange="1.21.1"
    ordering="AFTER"
    side="BOTH"